# Created by Haiping Lu by modifying https://github.com/HaozhiQi/ISONet/blob/master/configs/IN1k-ISO18.yaml (under the MIT License)
DATASET:
  NAME: CIFAR10
  NUM_CLASSES: 10
  NUM_WORKERS: 1
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 1e-4
  TRAIN_BATCH_SIZE: 128
  WARMUP: True
  WARMUP_EPOCH: 5
  WARMUP_FACTOR: 0.2
  MAX_EPOCHS: 100  # For quick testing
ISON:
  DEPTH: 38 # From an ECCV18 paper: ResNet with depth 38, 74, 110, 152 (6n+2) for CIFAR
  ORTHO_COEFF: 1e-4
  HAS_BN: False
  HAS_ST: False
  SReLU: True
  DIRAC_INIT: True
  DROPOUT: True
  DROPOUT_RATE: 0.1
